import type { Metadata } from "next";
import { Poiret_One, Martian_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";

const poiretOne = Poiret_One({
  weight: "400",
  variable: "--font-poiret-one"
})

const martianMono = Martian_Mono({
  weight: "400",
  variable: "--font-martian-mono"
})

export const metadata: Metadata = {
  title: "Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${poiretOne.variable} ${martianMono.variable} antialiased`}
      >
        <header>
          <Navbar />
        </header>

        <main>
          <div id="outlet">
            {children}
          </div>
        </main>

        <Footer />
      </body>
    </html>
  );
}
